-- MySQL Script generated by MySQL Workbench
-- 11/02/16 09:20:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema assessstaff
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assessstaff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assessstaff` DEFAULT CHARACTER SET utf8 ;
USE `assessstaff` ;

-- -----------------------------------------------------
-- Table `assessstaff`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessstaff`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assessstaff`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessstaff`.`user_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `gender` ENUM('F', 'M') NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `major` VARCHAR(500) NULL DEFAULT NULL,
  `ofice` VARCHAR(500) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assessstaff`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessstaff`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(225) NULL DEFAULT NULL,
  `password` VARCHAR(225) NULL DEFAULT NULL,
  `email` VARCHAR(225) NULL DEFAULT NULL,
  `user_info_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_info1_idx` (`user_info_id` ASC),
  CONSTRAINT `fk_user_user_info1`
    FOREIGN KEY (`user_info_id`)
    REFERENCES `assessstaff`.`user_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assessstaff`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessstaff`.`user_role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`role_id`, `user_id`),
  INDEX `fk_table2_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_table2_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `assessstaff`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table2_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `assessstaff`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
